import type { UseCase } from "@/lib/types";

export const useCases: UseCase[] = [
  {
    id: "UCA01",
    workflow: "WF0",
    actor: "Guest",
    name: "Register",
    description: "Bệnh nhân đăng ký tài khoản bằng email hoặc số điện thoại.",
  },
  {
    id: "UCA02",
    workflow: "WF0",
    actor: "All",
    name: "Login / Logout",
    description: "Đăng nhập đa vai trò và phân quyền theo actor.",
  },
  {
    id: "UCA03",
    workflow: "WF0",
    actor: "All",
    name: "Forgot Password",
    description: "Gửi yêu cầu reset mật khẩu qua email.",
  },
  {
    id: "UCA04",
    workflow: "WF0",
    actor: "All",
    name: "Profile Management",
    description: "Cập nhật thông tin cá nhân, số điện thoại, địa chỉ và ảnh đại diện.",
  },
  {
    id: "UCA05",
    workflow: "WF1",
    actor: "Admin",
    name: "Manage Dental Services",
    description: "CRUD danh mục dịch vụ, thời lượng và đơn giá.",
  },
  {
    id: "UCA06",
    workflow: "WF1",
    actor: "Admin",
    name: "Manage Dentist Profiles",
    description: "CRUD hồ sơ nha sĩ, chuyên môn, kinh nghiệm và trạng thái.",
  },
  {
    id: "UCA07",
    workflow: "WF1",
    actor: "Dentist",
    name: "Manage Work Schedule",
    description: "Thiết lập lịch làm việc theo tuần với slot 30 phút.",
  },
  {
    id: "UCA08",
    workflow: "WF1",
    actor: "Admin",
    name: "Manage Clinic Info",
    description: "Cập nhật thông tin phòng khám và giờ hoạt động.",
  },
  {
    id: "UCA09",
    workflow: "WF2",
    actor: "Patient",
    name: "Book Appointment",
    description: "Chọn dịch vụ, nha sĩ, ngày giờ và xác nhận đặt lịch.",
  },
  {
    id: "UCA10",
    workflow: "WF2",
    actor: "Receptionist",
    name: "Confirm Appointment",
    description: "Xác nhận hoặc từ chối lịch hẹn đang chờ.",
  },
  {
    id: "UCA11",
    workflow: "WF2",
    actor: "Receptionist",
    name: "Check-in Patient",
    description: "Check-in bệnh nhân khi tới phòng khám.",
  },
  {
    id: "UCA12",
    workflow: "WF2",
    actor: "Dentist",
    name: "Record Treatment Result",
    description: "Ghi chẩn đoán, thủ thuật, đơn thuốc và hẹn tái khám.",
  },
  {
    id: "UCA13",
    workflow: "WF2",
    actor: "Patient / Receptionist",
    name: "Cancel Appointment",
    description: "Hủy lịch hẹn trước tối thiểu 24 giờ.",
  },
  {
    id: "UCA14",
    workflow: "WF2",
    actor: "Patient / Receptionist",
    name: "Reschedule Appointment",
    description: "Dời lịch hẹn sang slot còn trống.",
  },
  {
    id: "UCA15",
    workflow: "WF2",
    actor: "Receptionist",
    name: "Handle No-show",
    description: "Đánh dấu bệnh nhân không đến và ghi chú follow-up.",
  },
  {
    id: "UCA16",
    workflow: "WF3",
    actor: "Admin / Receptionist",
    name: "Appointment Dashboard",
    description: "Tổng quan lịch hẹn hôm nay, tuần và tháng.",
  },
  {
    id: "UCA17",
    workflow: "WF3",
    actor: "Admin",
    name: "Revenue Report",
    description: "Thống kê doanh thu theo dịch vụ, nha sĩ và thời gian.",
  },
  {
    id: "UCA18",
    workflow: "WF3",
    actor: "Admin",
    name: "Patient Statistics",
    description: "Thống kê bệnh nhân mới, bệnh nhân tái khám và tỉ lệ no-show.",
  },
  {
    id: "UCA19",
    workflow: "WF2",
    actor: "Nurse",
    name: "Record Patient Vitals",
    description: "Ghi huyết áp, mạch, nhiệt độ, cân nặng và lý do khám.",
  },
  {
    id: "UCA20",
    workflow: "WF2",
    actor: "Nurse",
    name: "Prepare Treatment Room",
    description: "Chuẩn bị phòng, ghế, dụng cụ và vật tư trước ca khám.",
  },
  {
    id: "UCA21",
    workflow: "WF2",
    actor: "Nurse",
    name: "Assist Dentist Notes",
    description: "Ghi chú hỗ trợ trong quá trình điều trị theo phân công.",
  },
  {
    id: "UCA22",
    workflow: "WF2",
    actor: "Nurse",
    name: "Post-care Instructions",
    description: "Ghi dặn dò sau điều trị và hướng dẫn chăm sóc tại nhà.",
  },
  {
    id: "UCA23",
    workflow: "WF2",
    actor: "Nurse",
    name: "Inventory Consumption",
    description: "Ghi nhận vật tư đã dùng và đề xuất bổ sung khi tồn kho thấp.",
  },
  {
    id: "UCA24",
    workflow: "WF2",
    actor: "Nurse",
    name: "Sterilization Checklist",
    description: "Theo dõi checklist vô trùng dụng cụ giữa các ca điều trị.",
  },
  {
    id: "UCA25",
    workflow: "WF1",
    actor: "Admin",
    name: "Staff Management",
    description: "Tạo và cập nhật tài khoản nha sĩ, lễ tân, y tá và quản lý.",
  },
  {
    id: "UCA26",
    workflow: "WF1",
    actor: "Admin / Nurse",
    name: "Inventory Management",
    description: "Quản lý tồn kho vật tư, ngưỡng cảnh báo và đơn vị tính.",
  },
  {
    id: "UCA27",
    workflow: "WF2",
    actor: "Receptionist",
    name: "Appointment Reminder",
    description: "Theo dõi lịch cần nhắc và trạng thái liên hệ bệnh nhân.",
  },
  {
    id: "UCA28",
    workflow: "WF2",
    actor: "Dentist / Nurse",
    name: "Treatment History Search",
    description: "Tra cứu lịch sử khám và hồ sơ điều trị theo bệnh nhân.",
  },
  {
    id: "UCA29",
    workflow: "WF2",
    actor: "Receptionist",
    name: "No-show Follow-up",
    description: "Tạo ghi chú chăm sóc lại với các ca không đến.",
  },
  {
    id: "UCA30",
    workflow: "WF3",
    actor: "Admin",
    name: "Audit Activity Log",
    description: "Theo dõi thay đổi chính trên lịch hẹn, dịch vụ và hồ sơ.",
  },
];
